import Head from "next/head";
import { Inter } from "@next/font/google";
import Navbar from "@/components/Layout/Navbar";
import Hero from "@/components/Home/Hero";
import Explanation from "@/components/Home/Explanation";
import Process from "@/components/Home/Process";
import Cards from "@/components/Home/Cards";
import Newsletter from "@/components/Layout/Newsletter";
import Footer from "@/components/Layout/Footer";


const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  return (
    <>
      <Head>
        <title>Will Squire</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div>
        <Hero />
        <Explanation/>
        <Process/>
        <Cards/>
        <Newsletter/>
        <Footer/>
      </div>
    </>
  );
}
